[tool.poetry]
name = "rag-chat-app"
version = "0.1.0"
description = ""
authors = ["Kenfj <44661517+kenfj@users.noreply.github.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = {version = "^0.112.0", extras = ["standard"]}
pydantic-settings = "^2.6.1"
litellm = "^1.48.0"
azure-search-documents = "^11.5.1"
chainlit = "^1.2.0"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
pytest = "^8.3.3"
pytest-cov = "^6.0.0"
pytest-asyncio = "^0.24.0"
pytest-mock = "^3.14.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
line_length = 88
skip = ["__init__.py"]

# https://docs.pytest.org/en/stable/reference/customize.html
[tool.pytest.ini_options]
pythonpath = [
  "./src"
]
filterwarnings = [
  "ignore::DeprecationWarning:litellm.*:",
  "ignore::DeprecationWarning:pydantic.*:",
  "ignore::DeprecationWarning:importlib.*:",
]
# https://github.com/pytest-dev/pytest-asyncio/issues/924
asyncio_default_fixture_loop_scope="function"

# https://coverage.readthedocs.io/en/latest/source.html
[tool.coverage.run]
omit = [
    "__init__.py",
    "src/repositories/*",
    "src/my_cl_app.py",
    ]
